name: Test release

on:
  pull_request:
    paths-ignore:
      - 'documentation/**'

jobs:
  Release:
    name: Test release
    runs-on: [ubuntu-latest]
    container:
      image: gohornet/goreleaser-cgo-cross-compiler:1.16.7
      volumes: [/repo]

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test HORNET Release
        run: goreleaser --snapshot --skip-publish --rm-dist
